version: '3'

services:
  drupal-test-1:
    image: drupal:latest #this it's the latest image for drupal
    ports: 
      - '8080:80' #redirects ports from 80 to 8080
    environment: 
      POSTGRES_USER: user # sets a user for the postgres database, required
      POSTGRES_PASSWORD: pass # sets a password for the postgres database
      POSTGRES_DB: postgres-test-1 # sets a name for postgres database
      POSTGRES_HOST: postgres-test-1 # recently added to fix localhost issue on setup
    volumes:
      - /var/www/html/modules #stores modules data from drupal
      - /var/www/html/profiles #stores profiles data from drupal
      - /var/www/html/sites #stores sites data from drupal
      - /var/www/html/themes #stores themes data from drupal

  postgres-test-1:
    image: postgres:latest #the latest image for postgres
    restart: always
    ports:
      - '5432:5432'
    volumes: 
      - /var/lib/postgresql/data #added a volume for the db
